apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}
spec:
  #type: ClusterIP
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
    nodePort: 30100
  selector:
    app: search_engine
    component: ui
    release: {{ .Release.Name }}