apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host | default .Release.Name }}
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: {{ template "ui.fullname" . }}
            port: 
              number: {{ .Values.service.externalPort }}
        path: /    