apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search_engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search_engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        env:
        - name: RABBITMQ
          value: {{ .Values.rabbitmq | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: UI_DB
          value: {{ .Values.ui_dbHost | default (printf "%s-ui_db" .Release.Name) }}